version: "3.2"

services:
  seq:
    image: datalust/seq:latest
    restart: always
    ports:
      - 5380:80
      - 5341:5341
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seqData:/data

volumes:
  seqData:
