version: "3.2"

services:
  mysql:
    image: mysql:8.0.13
    restart: always
    command:
      [
        "mysqld",
        "--sql-mode=",
        "--default-authentication-plugin=mysql_native_password",
      ]
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mysqlData:/var/lib/mysql

volumes:
  mysqlData:
