version: "3.2"

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresData:/var/lib/postgresql/data

volumes:
  postgresData:
